export const specializations = [
    "Cardiology",
    "Orthopedics",
    "Dermatology",
    "Neurology",
    "Pediatrics",
    "Radiology",
    "GeneralSurgery",
    "Anaesthetist",
    "Oncology",
    "Ophthalmology",
    "Psychiatry",
    "Urology",
    "Endocrinology",
    "Gastroenterology",
    "Rheumatology",
    "Pulmonology",
    "Nephrology",
    "ObstetricsGynecology",
    "EmergencyMedicine",
    "FamilyMedicine",
    "InstrumentingNurse",
    "CirculatingNurse",
    "NurseAnaesthetist",
    "MedicalActionAssistant"
].map(name => ({ name }));  // Mapeia as strings para objetos com a chave 'name'
